Sperentia - SGI/Controllers/VacacionesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Sperientia___SGI.Filtros;
using Sperientia___SGI.Models.dbModels;
using Sperientia___SGI.Models.dbModels.DbContext;
using Sperientia___SGI.ViewModel;
using System.Security.Claims;

namespace Sperientia___SGI.Controllers
{
    [ValidarAdmin]
    public class VacacionesController : Controller
    {
        private readonly SperientiaContext _context;

        public VacacionesController(SperientiaContext context)
        {
            _context = context;

        }
        public async Task<IActionResult> Solicitudes()
        {
            var solicitudes = await _context.SolicitudVacaciones
                .Include(x => x.SolicitudVacacionesEstatu)
                .Include(x => x.SolicitudVacacionesDias)
                .Include(x => x.UsuarioLogin_IdUsuarioRh)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                    .ThenInclude(x => x.UsuarioInformacion)
                .ToListAsync();

            var model = new VacacionesViewModel
            {
                Estatus = _context.SolicitudVacacionesEstatus
               .Select(b => new SelectListItem
               {
                   Value = b.IdEstatus.ToString(),
                   Text = b.Descripcion
               }).ToList(),
               Solicitudes = solicitudes
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Solicitudes(IFormCollection form)
        {
            int? estatusSeleccionado = string.IsNullOrEmpty(form["estatusId"]) ? (int?)null : Convert.ToInt32(form["estatusId"]);
            
            IQueryable<SolicitudVacaciones> query = _context.SolicitudVacaciones
                .Include(x => x.SolicitudVacacionesEstatu)
                .Include(x => x.SolicitudVacacionesDias)
                .Include(x => x.UsuarioLogin_IdUsuarioRh)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                    .ThenInclude(x => x.UsuarioInformacion);

            if (estatusSeleccionado.HasValue)
                query = query.Where(x => x.IdEstatus == estatusSeleccionado.Value);

           
            var solicitudFiltrada = await query.ToListAsync();

            var model = new VacacionesViewModel
            {
                Estatus = _context.SolicitudVacacionesEstatus
               .Select(b => new SelectListItem
               {
                   Value = b.IdEstatus.ToString(),
                   Text = b.Descripcion,
                   Selected = (estatusSeleccionado.HasValue && b.IdEstatus == estatusSeleccionado.Value)
               }).ToList(),
                Solicitudes = solicitudFiltrada
            };

            return View(model);
        }

        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitud = await _context.SolicitudVacaciones
                .Include(x => x.SolicitudVacacionesEstatu)
                .Include(x => x.SolicitudVacacionesDias)
                .Include(x => x.UsuarioLogin_IdUsuarioRh)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                    .ThenInclude(x => x.UsuarioInformacion)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                    .ThenInclude(x => x.UsuarioInformacion)
                        .ThenInclude(x => x.Empresa)
                .Include(x => x.UsuarioLogin_IdEmpleado)
                    .ThenInclude(x => x.UsuarioInformacion)
                        .ThenInclude(x => x.Departamento)
                .FirstOrDefaultAsync(m => m.IdSolicitud == id);

            if (solicitud == null)
            {
                return NotFound();
            }

            int diasAcumulados = _context.SolicitudVacacionesDias
                .Join(_context.SolicitudVacaciones,
                      dia => dia.IdSolicitud,
                      sol => sol.IdSolicitud,
                      (dia, sol) => new { dia, sol })
                .Where(x => x.sol.IdEmpleado == solicitud.IdEmpleado && x.sol.IdEstatus == 2)
                .Count();
            int diasPedidos = _context.SolicitudVacacionesDias
                    .Where(d => d.IdSolicitud == solicitud.IdSolicitud).Count();
            int diasRestantes = diasAcumulados == 0
                ? solicitud.DerechoDiasEmpleado - diasPedidos
                : solicitud.DerechoDiasEmpleado - diasAcumulados - diasPedidos;

            string alerta = diasRestantes < 0
                ? "¡Advertencia! Se han solicitado más días de los que se tiene disponibles."
                : null;

            var viewModel = new VacacionesViewModel
            {
                Vacaciones = solicitud,
                DiasPedidos = _context.SolicitudVacacionesDias
                    .Where(d => d.IdSolicitud == solicitud.IdSolicitud)
                    .OrderBy(d => d.Fecha) 
                    .ToList(),
                DiasAcumulados = diasAcumulados,
                DiasRestantes = diasRestantes,
                AlertaDiasRestantes = alerta
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ActualizarEstatus(int idSolicitud, int idEstatus)
        {
            int currentUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var solicitud = await _context.SolicitudVacaciones.FindAsync(idSolicitud);
            if (solicitud != null)
            {
                solicitud.IdUsuarioRh = currentUserId;
                solicitud.IdEstatus = idEstatus;
                await _context.SaveChangesAsync();
                TempData["Mensaje"] = "Estatus de la solicitud actualizado correctamente";
            }

            return RedirectToAction("Solicitudes");
        }
    }
}

Sperentia - SGI/Views/Vacaciones/Detalles.cshtml
@model Sperientia___SGI.ViewModel.VacacionesViewModel

@{
    ViewData["Title"] = "Detalles Solicitud Vacaciones";
    Layout = "_LayoutAdmin";
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card ">
                <div class="card-body ">
                    <h5 class="card-title text-center pb-0 fs-4">Vacaciones | Detalles</h5>
                    <br />
                    <div class="d-flex  justify-content-center">
                        <form asp-action="ActualizarEstatus" method="post">
                            <input type="hidden" name="IdSolicitud" value="@Model.Vacaciones.IdSolicitud" />
                            <input type="hidden" id="IdEstatus" name="IdEstatus" value="" />
                            @* DATOS DE COLABORADOR *@
                            <h5 class="card-title">Datos de colaborador</h5>
                            <div class="row mb-3">
                                <label for="numColab" class="col-md-5 col-lg-6 col-form-label">No. empleado</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.UsuarioInformacion.NumeroColaborador
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="nombre" class="col-md-5 col-lg-6 col-form-label">Nombre</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.NombreCompleto
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="puesto" class="col-md-5 col-lg-6 col-form-label">Titulo o puesto</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.UsuarioInformacion.Puesto
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="empresa" class="col-md-5 col-lg-6 col-form-label">Empresa</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.UsuarioInformacion.Empresa.Nombre
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="departamento" class="col-md-5 col-lg-6 col-form-label">Departamento</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.UsuarioInformacion.Departamento.Nombre
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="superior" class="col-md-5 col-lg-6 col-form-label">Superior</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdEmpleado.UsuarioInformacion.UsuarioLogin_IdSupervisor?.NombreCompleto
                                    </label>
                                </div>
                            </div>
                            <hr />
                            @* INFORMACION DE SOLICITUD *@
                            <h5 class="card-title">Información de solicitud</h5>
                            <div class="row mb-3">
                                <label for="fechaSol" class="col-md-5 col-lg-6 col-form-label">Fecha de solicitud</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.FechaSolicitud.ToString("dd - MMMM - yyyy")
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="diasDis" class="col-md-5 col-lg-6 col-form-label">Dias disponibles</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.DerechoDiasEmpleado
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="diasSol" class="col-md-5 col-lg-6 col-form-label">Dias solicitados</label>
                                <div class="col-md-7 col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        @foreach (var dia in Model.DiasPedidos)
                                        {
                                            <li>@dia.Fecha.ToString("dd - MMMM - yyyy")</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                            <hr />
                            @* DISPONIBILIDAD DE VACACIONES *@
                            <h5 class="card-title">Disponibilidad de vacaciones</h5>
                            <div class="row mb-3">
                                <label for="diasAcum" class="col-md-5 col-lg-6 col-form-label">Dias acumulados</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">@Model.DiasAcumulados</label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="diasRes" class="col-md-5 col-lg-6 col-form-label">Dias restantes (después de aprobar)</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">@Model.DiasRestantes</label>
                                </div>
                            </div>

                            @if (!string.IsNullOrEmpty(Model.AlertaDiasRestantes))
                                {
                                <div class="row mb-3 alert alert-danger" role="alert">
                                    <div class="col-md-12" role="alert">
                                            <span class="text-danger fw-bold">@Model.AlertaDiasRestantes</span>
                                        </div>
                                    </div>
                                }

                            <hr />
                            @* SUSTITUTO DURANTE AUSENCIA *@
                            <h5 class="card-title">Datos Sustituto</h5>
                            <div class="row mb-3">
                                <label for="sustituto" class="col-md-5 col-lg-6 col-form-label">Nombre</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.SustitutoNombre
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="contacto" class="col-md-5 col-lg-6 col-form-label">Teléfono</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.SustitutoTelefono
                                    </label>
                                </div>
                            </div>
                            <hr />
                            @* AUTORIZACIONES *@
                            <h5 class="card-title">Autorización</h5>
                            <div class="row mb-3">
                                <label for="RH" class="col-md-5 col-lg-6 col-form-label">Representante de RH</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="numColab" class="col-form-label">
                                        @Model.Vacaciones.UsuarioLogin_IdUsuarioRh?.NombreCompleto
                                    </label>
                                </div>
                            </div>

                            <br />
                            <div class="row mb-3">

                                <div class="btn-group" role="group">
                                    <button type="button" class="btn btn-sm btn-warning me-2" onclick="location.href='@Url.Action("Solicitudes", "Vacaciones")'">Volver</button>
                                    <button type="submit" class="btn btn-sm btn-danger me-2" onclick="document.getElementById('IdEstatus').value = 3">Rechazar</button>
                                    <button type="submit" class="btn btn-sm btn-success" onclick="document.getElementById('IdEstatus').value = 2">Autorizar</button>
                                    @* <button type="button" class="btn btn-sm btn-danger me-2" data-bs-toggle="modal" data-bs-target="#verticalycentered">Rechazar</button> *@
                                    @* <button type="button" class="btn btn-sm btn-success" >Autorizar</button> *@
                                    @* <a asp-action="Autorizar" asp-route-id="@Model.Vacaciones.IdSolicitud" type="button" class="btn btn-success" data-bs-dismiss="modal">Autorizar</a> *@
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>

@* 
<div class="modal fade" id="verticalycentered" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered  modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="bi bi-exclamation-triangle"></i> Rechazar solicitud</h5>
            </div>
            <div class="modal-body">
                <div class=" d-flex w-80 justify-content-center">
                    @TempData["Message"]
                </div>
            </div>
        </div>
    </div>
</div> *@

Sperentia - SGI/Views/Vacaciones/Solicitudes.cshtml
@model Sperientia___SGI.ViewModel.VacacionesViewModel

@{
    ViewData["Title"] = "Solicitudes Vacaciones";
    Layout = "_LayoutAdmin";
}


<style>
    .table td, .table th {
        vertical-align: middle !important;
        text-align: center !important;
    }

    .datatable tbody td {
        cursor: pointer;
    }

</style>

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center pb-0 fs-4">Vacaciones | Solicitudes</h5>
                    </br>
                    <form asp-action="Solicitudes" method="post">

                        <div class="row mb-3 align-items-center">
                            <div class="col-1">
                                <label for="empleado" class="col-form-label">Estado</label>
                            </div>
                            <div class="col-3">
                                <select class="form-select" aria-label="Seleccionar estatus" asp-items="Model.Estatus" name="estatusId">
                                    <option value="" selected>--Todos--</option>
                                </select>
                            </div>

                            <div class="form-actions form-group col-auto">
                                <button type="submit" class="btn btn-primary btn-sm">Filtrar</button>
                            </div>
                        </div>
                    </form>

                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>No. Empleado</th>
                                <th>Dias pedidos</th>
                                <th>Fecha Solicitud</th>
                                <th>Estado</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model.Solicitudes != null && Model.Solicitudes.Any())
                            {
                                foreach (var emp in Model.Solicitudes)
                                {
                                    <tr>
                                        <td>@emp.UsuarioLogin_IdEmpleado.UsuarioInformacion.NumeroColaborador</td>
                                        <td>@emp.SolicitudVacacionesDias.Count()</td>
                                        <td>@emp.FechaSolicitud.ToString("dd-MM-yyyy")</td>
                                        <td class="
                                            @(
                                                emp.SolicitudVacacionesEstatu.Descripcion == "Aprobado" ? "bg-success text-white" :
                                                emp.SolicitudVacacionesEstatu.Descripcion == "No aprobado" ? "bg-danger text-white" :
                                                emp.SolicitudVacacionesEstatu.Descripcion == "Pendiente" ? "bg-warning text-dark" :
                                                ""
                                            )">
                                            @emp.SolicitudVacacionesEstatu.Descripcion
                                        </td>
                                        <td>
                                            <a asp-action="Detalles" asp-route-id="@emp.IdSolicitud"
                                               class="btn btn-primary rounded-pill btn-sm"><i class="bi bi-info-lg"></i></a>
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</section>

<!-- Modal con mensaje -->
<div class="modal fade" id="mensajeModal" tabindex="-1" aria-labelledby="mensajeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mensajeModalLabel">
                    <a class="btn btn-primary rounded-pill btn-sm">
                        <i class="bi bi-info-lg"></i>
                    </a> Información
                </h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                @if (TempData["Mensaje"] != null)
                {
                    <p>@TempData["Mensaje"]</p>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

        $(document).ready(function () {
        @if (TempData["Mensaje"] != null)
        {
            <text>
                              $('#mensajeModal').modal('show');
            </text>
        }
        });

    </script>
}