Sperentia - SGI/Models/dbModels/Inventario.cs
namespace Sperientia___SGI.Models.dbModels
{
    // Inventario
    public class Inventario
    {
        public int IdInventario { get; set; } // IdInventario (Primary key)
        public string CodigoInterno { get; set; } // CodigoInterno (length: 50)
        public string Foto { get; set; } // Foto (length: 500)
        public string Nombre { get; set; } // Nombre (length: 100)
        public string Descripcion { get; set; } // Descripcion (length: 500)
        public int IdCategoria { get; set; } // IdCategoria
        public DateTime? FechaCompra { get; set; } // FechaCompra
        public decimal? Costo { get; set; } // Costo
        public string Proveedor { get; set; } // Proveedor (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child InventarioAsignacions where [InventarioAsignacion].[IdInventario] point to this entity (FK_InventarioAsignacion_Inventario)
        /// </summary>
        public ICollection<InventarioAsignacion> InventarioAsignacions { get; set; } // InventarioAsignacion.FK_InventarioAsignacion_Inventario

        /// <summary>
        /// Parent (One-to-One) Inventario pointed by [InventarioGeneral].[IdInventario] (FK_InventarioGeneral_Inventario)
        /// </summary>
        public InventarioGeneral InventarioGeneral { get; set; } // InventarioGeneral.FK_InventarioGeneral_Inventario

        /// <summary>
        /// Parent (One-to-One) Inventario pointed by [InventarioLibro].[IdInventario] (FK_InventarioLibro_Inventario)
        /// </summary>
        public InventarioLibro InventarioLibro { get; set; } // InventarioLibro.FK_InventarioLibro_Inventario

        // Foreign keys

        /// <summary>
        /// Parent InventarioCategoria pointed by [Inventario].([IdCategoria]) (FK_Inventario_Categoria)
        /// </summary>
        public InventarioCategoria InventarioCategoria { get; set; } // FK_Inventario_Categoria

        public Inventario()
        {
            InventarioAsignacions = new List<InventarioAsignacion>();
        }
    }
}

Sperentia - SGI/Controllers/InventarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sperientia___SGI.Filtros;
using Sperientia___SGI.Models.dbModels;
using Sperientia___SGI.Models.dbModels.DbContext;
using Sperientia___SGI.ViewModel;
using System.Security.Claims;

namespace Sperientia___SGI.Controllers
{
    [ValidarAdmin]
    public class InventarioController : Controller
    {
        private readonly SperientiaContext _context;

        public InventarioController(SperientiaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _context.Inventarios
                .Include(x => x.InventarioCategoria)
                .ToListAsync();

            return View(model);

        }

        public IActionResult Create()
        {

            var inventarioVM = new InventarioViewModel
            {
                InventarioCategoria = _context.InventarioCategorias
                   .Select(b => new SelectListItem
                   {
                       Value = b.IdCategoria.ToString(),
                       Text = b.Nombre
                   }).ToList(),
                Inventario = new Inventario(),
                Libro = new InventarioLibro(),
                General = new InventarioGeneral()
            };

            return View(inventarioVM);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(InventarioViewModel model)
        {
            var rutaBase = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/inv");

            try
            {
                var inventarioId = model.Inventario.IdInventario;
                var baseD = Directory.GetCurrentDirectory();

                if (!Directory.Exists(rutaBase))
                    Directory.CreateDirectory(rutaBase);

                // Guardar foto
                if (model.Fotografia != null && model.Fotografia.Length > 0)
                {
                    var nombreArchivo = $"foto_{inventarioId}_{Path.GetFileName(model.Fotografia.FileName)}";
                    var rutaCompleta = Path.Combine(rutaBase, nombreArchivo);

                    using (var stream = new FileStream(rutaCompleta, FileMode.Create))
                    {
                        await model.Fotografia.CopyToAsync(stream);
                    }

                    model.Inventario.Foto = $"/img/inv/{nombreArchivo}";
                }

                //guardar datos inventario
                _context.Inventarios.Add(model.Inventario);
                await _context.SaveChangesAsync();

                if (model.Inventario.IdCategoria == 1)
                {
                    model.Libro.IdInventario = model.Inventario.IdInventario;
                    _context.InventarioLibroes.Add(model.Libro);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    model.General.IdInventario = model.Inventario.IdInventario;
                    _context.InventarioGenerals.Add(model.General);
                    await _context.SaveChangesAsync();
                }

            }

            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");

            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios
                .Include(d => d.InventarioCategoria)
                .Include(d => d.InventarioLibro)
                .FirstOrDefaultAsync(m => m.IdInventario == id);
           


            if (inventario == null)
            {
                return NotFound();
            }

            var general = await _context.InventarioGenerals
               .Include(d => d.Inventario)
               .FirstOrDefaultAsync(m => m.IdInventario == id);

            var libro = await _context.InventarioLibroes
                .Include(d => d.Inventario)
                .FirstOrDefaultAsync(m => m.IdInventario == id);

            var viewModel = new InventarioViewModel
            {
                Inventario = inventario,
                Libro = libro,
                General = general
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Modificar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios
                .Include(d => d.InventarioCategoria)
                .FirstOrDefaultAsync(m => m.IdInventario == id);

            if (inventario == null)
            {
                return NotFound();
            }


            var general = await _context.InventarioGenerals
               .Include(d => d.Inventario)
               .FirstOrDefaultAsync(m => m.IdInventario == id);

            var libro = await _context.InventarioLibroes
                .Include(d => d.Inventario)
                .FirstOrDefaultAsync(m => m.IdInventario == id);

            var viewModel = new InventarioViewModel
            {
                InventarioCategoria = _context.InventarioCategorias.Select(t => new SelectListItem
                {
                    Value = t.IdCategoria.ToString(),
                    Text = t.Nombre
                }).ToList(),
                Inventario = inventario,
                Libro = libro,
                General = general
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarRegistro(InventarioViewModel model)
        {
            var rutaBase = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/inv");

            try
            {
                if (model.Fotografia != null && model.Fotografia.Length > 0)
                {
                    var nombreCorto = Convert.ToBase64String(Guid.NewGuid().ToByteArray())
                        .Replace("=", "").Replace("+", "").Replace("/", "")
                        .Substring(0, 8);
                    var nuevoNombre = $"img_{nombreCorto}{Path.GetExtension(model.Fotografia.FileName)}";
                    var nuevaRuta = Path.Combine(rutaBase, nuevoNombre);

                    using (var stream = new FileStream(nuevaRuta, FileMode.Create))
                        await model.Fotografia.CopyToAsync(stream);

                    model.Inventario.Foto = $"/img/inv/{nuevoNombre}";
                }

                var inventarioExiste = await _context.Inventarios
                   .FirstOrDefaultAsync(x => x.IdInventario == model.Inventario.IdInventario);

                if (inventarioExiste != null)
                {
                    inventarioExiste.CodigoInterno = model.Inventario.CodigoInterno;
                    inventarioExiste.Nombre = model.Inventario.Nombre;
                    inventarioExiste.IdCategoria = model.Inventario.IdCategoria;
                    inventarioExiste.Descripcion = model.Inventario.Descripcion;
                    inventarioExiste.Proveedor = model.Inventario.Proveedor;
                    inventarioExiste.FechaCompra = model.Inventario.FechaCompra;
                    inventarioExiste.Costo = model.Inventario.Costo;
                    inventarioExiste.Foto =
                        !string.IsNullOrEmpty(model.Inventario.Foto)
                          ? model.Inventario.Foto
                          : inventarioExiste.Foto;

                    _context.Update(inventarioExiste);
                }

                if (model.Inventario.IdCategoria == 1)
                {
                    var libroExiste = await _context.InventarioLibroes
                  .FirstOrDefaultAsync(x => x.IdInventario == model.Libro.IdInventario);

                    if (libroExiste != null)
                    {
                        libroExiste.Autor = model.Libro.Autor;
                        libroExiste.Reseña = model.Libro.Reseña;
                        libroExiste.Isbn = model.Libro.Isbn;
                        libroExiste.Editorial = model.Libro.Editorial;
                        libroExiste.EsDigital = model.Libro.EsDigital;

                        _context.Update(libroExiste);
                    }
                }
                else
                {
                    var generalExiste = await _context.InventarioGenerals
                   .FirstOrDefaultAsync(x => x.IdInventario == model.General.IdInventario);

                    if (generalExiste != null)
                    {
                        generalExiste.Marca = model.General.Marca;
                        generalExiste.Modelo = model.General.Modelo;
                        generalExiste.NumeroSerie = model.General.NumeroSerie;
                        generalExiste.EstadoCondicion = model.General.EstadoCondicion;
                        generalExiste.GarantiaFechaFin = model.General.GarantiaFechaFin;

                        _context.Update(generalExiste);
                    }
                }
                
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Registro actualizado correctamente";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocurrió un error al actualizar el registro");
                return RedirectToAction("Index");
            }
        }
    }
}

Sperentia - SGI/Views/Inventario/Create.cshtml
@model Sperientia___SGI.ViewModel.InventarioViewModel

@{
    ViewData["Title"] = "Crear Inventario";
    Layout = "_LayoutAdmin";
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card ">
                <div class="card-body ">
                    <h5 class="card-title text-center pb-0 fs-4">Nuevo Inventario</h5>
                    <br />

                    <div class="m-4 d-flex  justify-content-center">
                        <form asp-action="Guardar" method="post" enctype="multipart/form-data">

                            <div class="row mb-3">
                                <label for="codigo" class="col-md-5 col-lg-6 col-form-label">Código Interno <span class="text-warning">*</span></label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="number" step="any" asp-for="Inventario.CodigoInterno">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="nombre" class="col-md-5 col-lg-6 col-form-label">Nombre <span class="text-warning">*</span></label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Inventario.Nombre">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="descripcion" class="col-md-5 col-lg-6 col-form-label">Descripción</label>
                                <div class="col-md-7 col-lg-6">
                                    <textarea class="form-control" id="floatingTextarea" style="height: 100px;" asp-for="Inventario.Descripcion"></textarea>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="categoria" class="col-md-5 col-lg-6 col-form-label">Categoria</label>
                                <div class="col-md-7 col-lg-6">
                                    <select id="categoria" asp-for="Inventario.IdCategoria" class="form-select" asp-items="Model.InventarioCategoria">
                                        <option>--Seleccione--</option>
                                    </select>
                                </div>
                            </div>

                            <div id = "divLibro" class="d-none">
                                <div class="row mb-3">
                                    <label for="autor" class="col-md-5 col-lg-6 col-form-label">Autor</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="Libro.Autor">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="editorial" class="col-md-5 col-lg-6 col-form-label">Editorial</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="Libro.Editorial">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="isbn" class="col-md-5 col-lg-6 col-form-label">ISBN</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="Libro.Isbn">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="reseña" class="col-md-5 col-lg-6 col-form-label">Reseña</label>
                                    <div class="col-md-7 col-lg-6">
                                        <textarea class="form-control" id="floatingTextarea" style="height: 100px;" asp-for="Libro.Reseña"></textarea>
                                    </div>
                                </div>

                                <div class="row mb-3 align-items-center">
                                    <label class="col-md-5 col-lg-6 col-form-label">Es Digital</label>
                                    <div class="col-md-7 col-lg-6 d-flex align-items-center gap-2">
                                        <input type="checkbox" class="form-check-input" asp-for="Libro.EsDigital" />
                                        <label class="mb-0">
                                            Sí
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div id="divGeneral" class="d-none">
                                <div class="row mb-3">
                                    <label for="marca" class="col-md-5 col-lg-6 col-form-label">Marca</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="General.Marca">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="modelo" class="col-md-5 col-lg-6 col-form-label">Modelo</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="General.Modelo">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="noSerie" class="col-md-5 col-lg-6 col-form-label">No. Serie</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="number" asp-for="General.NumeroSerie">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="condicion" class="col-md-5 col-lg-6 col-form-label">Condición</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="text" asp-for="General.EstadoCondicion">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="fechaG" class="col-md-5 col-lg-6 col-form-label">Fecha de Garantía</label>
                                    <div class="col-md-7 col-lg-6">
                                        <input class="form-control" type="date" asp-for="General.GarantiaFechaFin">
                                    </div>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="prov" class="col-md-5 col-lg-6 col-form-label">Proveedor</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Inventario.Proveedor">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="fechaC" class="col-md-5 col-lg-6 col-form-label">Fecha de compra</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="date" asp-for="Inventario.FechaCompra">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="costo" class="col-md-5 col-lg-6 col-form-label">Costo</label>
                                <div class="col-md-7 col-lg-6">
                                    <div class="input-group">
                                        <span class="input-group-text">$ </span>
                                        <input class="form-control" type="number" asp-for="Inventario.Costo">
                                    </div>
                                </div>
                            </div>


                            <div class="row mb-3">
                                <label for="foto" class="col-md-5 col-lg-6 col-form-label">Subir fotografia</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="file" name="Fotografia" asp-for="Inventario.Foto">

                                </div>
                            </div>


                            <br />
                            <div class="row mb-3">

                                <div class="d-inline-flex justify-content-center" role="group">
                                    <button type="button" class="btn btn-sm btn-warning me-2" onclick="location.href='@Url.Action("Index", "Inventario")'">Volver</button>
                                    <button type="submit" class="btn btn-sm btn-success">Crear</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>

@section Scripts {


    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const selectCategoria = document.getElementById('categoria');
            const divLibro = document.getElementById('divLibro');
            const divGeneral = document.getElementById('divGeneral');

            function toggleAutorDiv() {
                const selectedText = selectCategoria.options[selectCategoria.selectedIndex].text.toLowerCase();
                console.log(selectedText);
                if (selectedText === 'libro') {
                    divLibro.classList.remove('d-none');
                    divGeneral.classList.add('d-none');
                } else {
                    divLibro.classList.add('d-none');
                    divGeneral.classList.remove('d-none');
                }
            }

            selectCategoria.addEventListener('change', toggleAutorDiv);

            toggleAutorDiv();
        });
    </script>
}

Sperentia - SGI/Views/Inventario/Index.cshtml
@model IEnumerable<Sperientia___SGI.Models.dbModels.Inventario>

@{
    ViewData["Title"] = "Index";
    Layout = "_LayoutAdmin";
}


<style>
    .table td, .table th {
        vertical-align: middle !important;
        text-align: center !important;
    }

    .datatable tbody td {
        cursor: pointer;
    }

</style>

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center pb-0 fs-4">Inventario</h5>

                    <div class="col-lg-12 my-5 ">
                        <button type="button" class="btn btn-success mx-2" onclick="location.href='@Url.Action("Create", "Inventario")'">
                            <i class="bi bi-folder"></i> Crear
                        </button>
                    </div>

                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th style="width: 10%;">
                                    Foto
                                </th>
                                <th>Codigo Interno</th>
                                <th>Nombre</th>
                                <th>Categoria</th>
                                <th>Proveedor</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.IdInventario</td>
                                        <td>
                                            <img src="@item.Foto" class="img-fluid rounded-start">
                                        </td>
                                        <td>@item.CodigoInterno</td>
                                        <td>@item.Nombre</td>
                                        <td>@item.InventarioCategoria.Nombre</td>
                                        <td>@item.Proveedor</td>
                                        <td>
                                            <a asp-action="Detalles" asp-route-id="@item.IdInventario"
                                               class="btn btn-primary rounded-pill btn-sm"><i class="bi bi-info-lg"></i></a>
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</section>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        // $(".datatable tbody").on("click", "td", function () {
        //     var numeroColaborador = $(this).closest("tr").find("td:first").text().trim();
        //     var url = "/Inventario/Detalles/" + numeroColaborador; // Ajusta el controlador y acción
        //     window.open(url, "_self");
        // });
    });
</script>