Sperentia - SGI/Models/dbModels/Servicio.cs
namespace Sperientia___SGI.Models.dbModels
{
    // Servicio
    public class Servicio
    {
        public int IdServicio { get; set; } // IdServicio (Primary key)
        public string Nombre { get; set; } // Nombre (length: 100)
        public decimal Costo { get; set; } // Costo
        public int CostoDivisa { get; set; } // CostoDivisa
        public string CostoFrecuencia { get; set; } // CostoFrecuencia (length: 50)
        public string MetodoPago { get; set; } // MetodoPago (length: 100)
        public DateTime? FechaAdquisicion { get; set; } // FechaAdquisicion
        public string CuentaRegistrada { get; set; } // CuentaRegistrada (length: 256)
        public string Contrasena { get; set; } // Contrasena (length: 50)
        public DateTime? UltimaModificacionContrasena { get; set; } // UltimaModificacionContrasena
        public string Url { get; set; } // URL (length: 500)
        public string Notas { get; set; } // Notas (length: 1000)

        // Reverse navigation

        /// <summary>
        /// Child ServicioUsuarios where [ServicioUsuario].[IdServicio] point to this entity (FK_ServicioUsuario_Servicio)
        /// </summary>
        public ICollection<ServicioUsuario> ServicioUsuarios { get; set; } // ServicioUsuario.FK_ServicioUsuario_Servicio

        // Foreign keys

        /// <summary>
        /// Parent Divisa pointed by [Servicio].([CostoDivisa]) (FK_Servicio_Divisa)
        /// </summary>
        public Divisa Divisa { get; set; } // FK_Servicio_Divisa

        public Servicio()
        {
            ServicioUsuarios = new List<ServicioUsuario>();
        }
    }
}

Sperentia - SGI/Controllers/ServiciosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sperientia___SGI.Filtros;
using Sperientia___SGI.Models.dbModels;
using Sperientia___SGI.Models.dbModels.DbContext;
using Sperientia___SGI.ViewModel;

namespace Sperientia___SGI.Controllers
{
    [ValidarAdmin]
    public class ServiciosController : Controller
    {
        private readonly SperientiaContext _context;

        public ServiciosController(SperientiaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Servicios.ToListAsync());
        }

        public IActionResult Create()
        {

            var servicio = new ServiciosViewModel
            {
                Divisa = _context.Divisas
                .Select(b => new SelectListItem
                {
                    Value = b.IdDivisa.ToString(),
                    Text = b.Nombre
                }).ToList(),
                Servicio = new Servicio()
            };

            return View(servicio);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(ServiciosViewModel model)
        {
            try
            {
                //guardar datos servicio
                _context.Servicios.Add(model.Servicio);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .Include(x => x.Divisa)
                .FirstOrDefaultAsync(m => m.IdServicio == id);

            if (servicio == null)
            {
                return NotFound();
            }

            var viewModel = new ServiciosViewModel
            {
                Servicio = servicio
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Modificar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .Include(x => x.Divisa)
                .FirstOrDefaultAsync(m => m.IdServicio == id);

            if (servicio == null)
            {
                return NotFound();
            }

            var servicioVM = new ServiciosViewModel
            {
                Divisa = _context.Divisas.Select(t => new SelectListItem
                {
                    Value = t.IdDivisa.ToString(),
                    Text = t.Nombre
                }).ToList(),
                Servicio = servicio
            };

            return View(servicioVM);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarRegistro(ServiciosViewModel model)
        {

            try
            {
                var servicioExiste = await _context.Servicios
                   .FirstOrDefaultAsync(x => x.IdServicio == model.Servicio.IdServicio);

                if (servicioExiste != null)
                {
                    //servicioExiste.IdServicio = model.Servicio.IdServicio;
                    servicioExiste.Nombre = model.Servicio.Nombre;
                    servicioExiste.Costo = model.Servicio.Costo;
                    servicioExiste.CostoDivisa = model.Servicio.CostoDivisa;
                    servicioExiste.CostoFrecuencia = model.Servicio.CostoFrecuencia;
                    servicioExiste.MetodoPago = model.Servicio.MetodoPago;
                    servicioExiste.FechaAdquisicion = model.Servicio.FechaAdquisicion;
                    servicioExiste.CuentaRegistrada = model.Servicio.CuentaRegistrada;
                    servicioExiste.Url = model.Servicio.Url;
                    servicioExiste.Notas = model.Servicio.Notas;

                    if (servicioExiste.Contrasena != model.Servicio.Contrasena)
                    {
                        servicioExiste.Contrasena = model.Servicio.Contrasena;
                        servicioExiste.UltimaModificacionContrasena = DateTime.Today;
                    }

                    _context.Update(servicioExiste);
                }

                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Registro actualizado correctamente";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocurrió un error al actualizar el registro");
                return RedirectToAction("Index");
            }
        }
    }
}

Sperentia - SGI/Views/Servicios/Create.cshtml
@model Sperientia___SGI.ViewModel.ServiciosViewModel

@{
    ViewData["Title"] = "Crear Servicio";
    Layout = "_LayoutAdmin";
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card ">
                <div class="card-body ">
                    <h5 class="card-title text-center pb-0 fs-4">Crear Servicio</h5>
                    <br />

                    <div class="m-4 d-flex  justify-content-center">
                        <form asp-action="Guardar" method="post" enctype="multipart/form-data">


                            <div class="row mb-3">
                                <label for="nombre" class="col-md-5 col-lg-6 col-form-label">Nombre</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Nombre">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="costo" class="col-md-5 col-lg-6 col-form-label">Costo</label>
                                <div class="col-md-7 col-lg-6">
                                    <div class="input-group">
                                        <span class="input-group-text">$ </span>
                                        <input class="form-control" type="number" asp-for="Servicio.Costo">
                                    </div>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="divisa" class="col-md-5 col-lg-6 col-form-label">Divisa</label>
                                <div class="col-md-7 col-lg-6">
                                    <select asp-for="Servicio.CostoDivisa" class="form-select" asp-items="Model.Divisa">
                                        <option>--Seleccione--</option>
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="frecuencia" class="col-md-5 col-lg-6 col-form-label">Frecuencia de pago</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.CostoFrecuencia">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="metodo" class="col-md-5 col-lg-6 col-form-label">Método de pago</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.MetodoPago">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="fechaA" class="col-md-5 col-lg-6 col-form-label">Fecha de adquisición</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="date" asp-for="Servicio.FechaAdquisicion">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="cuenta" class="col-md-5 col-lg-6 col-form-label">Cuenta registrada</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.CuentaRegistrada">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="contrasena" class="col-md-5 col-lg-6 col-form-label">Contraseña</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Contrasena">
                                </div>
                            </div>

                           @*  <div class="row mb-3">
                                <label for="fechaM" class="col-md-5 col-lg-6 col-form-label">Última modificación</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="date" asp-for="Servicio.UltimaModificacionContrasena">
                                </div>
                            </div> *@

                            <div class="row mb-3">
                                <label for="url" class="col-md-5 col-lg-6 col-form-label">URL</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Url">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="notas" class="col-md-5 col-lg-6 col-form-label">Notas</label>
                                <div class="col-md-7 col-lg-6">
                                    <textarea class="form-control" id="floatingTextarea" style="height: 100px;" asp-for="Servicio.Notas">
                                    </textarea>
                                </div>
                            </div>

                            <br />
                            <div class="row mb-3">

                                <div class="d-inline-flex justify-content-center" role="group">
                                    <button type="button" class="btn btn-sm btn-warning me-2" onclick="location.href='@Url.Action("Index", "Servicios")'">Volver</button>
                                    <button type="submit" class="btn btn-sm btn-success">Crear</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>

Sperentia - SGI/Views/Servicios/Detalles.cshtml
@model Sperientia___SGI.ViewModel.ServiciosViewModel

@{
    ViewData["Title"] = "Detalles Servicio";
    Layout = "_LayoutAdmin";
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card ">
                <div class="card-body ">
                    <h5 class="card-title text-center pb-0 fs-4">Detalles</h5>
                    <br />

                    <div class="m-4 d-flex  justify-content-center">
                        <form>

                            <div class="row mb-3">
                                <label for="id" class="col-md-5 col-lg-6 col-form-label">Id servicio</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="id" class="col-form-label">
                                        @Model.Servicio.IdServicio
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="nombre" class="col-md-5 col-lg-6 col-form-label">Nombre</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="nombre" class="col-form-label">
                                        @Model.Servicio.Nombre
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="costo" class="col-md-5 col-lg-6 col-form-label">Costo</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="costo" class="col-form-label">
                                        $@Model.Servicio.Costo
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="divisa" class="col-md-5 col-lg-6 col-form-label">Divisa</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="divisa" class="col-form-label">
                                        @Model.Servicio.Divisa.Nombre
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="frecuencia" class="col-md-5 col-lg-6 col-form-label">Frecuencia de pago</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="frecuencia" class="col-form-label">
                                        @Model.Servicio.CostoFrecuencia
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="fechaA" class="col-md-5 col-lg-6 col-form-label">Fecha de adquisición</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="fechaA" class="col-form-label">
                                        @Model.Servicio.FechaAdquisicion?.ToString("dd 'de' MMMM 'de' yyyy")
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="cuenta" class="col-md-5 col-lg-6 col-form-label">Cuenta registrada</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="cuenta" class="col-form-label">
                                        @Model.Servicio.CuentaRegistrada
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="contrasena" class="col-md-5 col-lg-6 col-form-label">Contraseña</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="contrasena" class="col-form-label">
                                        @Model.Servicio.Contrasena
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="modificacion" class="col-md-5 col-lg-6 col-form-label">Última modificación</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="modificacion" class="col-form-label">
                                        @Model.Servicio.UltimaModificacionContrasena?.ToString("dd 'de' MMMM 'de' yyyy")
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="url" class="col-md-5 col-lg-6 col-form-label">URL</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="url" class="col-form-label">
                                        <a href="#">@Model.Servicio.Url</a>
                                    </label>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="notas" class="col-md-5 col-lg-6 col-form-label">Notas</label>
                                <div class="col-md-7 col-lg-6">
                                    <label for="notas" class="col-form-label">
                                        @Model.Servicio.Notas
                                    </label>
                                </div>
                            </div>

                            <br />
                            <div class="row mb-3">

                                <div class="d-inline-flex justify-content-center" role="group">
                                    <button type="button" class="btn btn-sm btn-warning me-2" onclick="location.href='@Url.Action("Index", "Servicios")'">Volver</button>
                                    @* <button type="button" class="btn btn-sm btn-danger me-2" data-bs-toggle="modal" data-bs-target="#verticalycentered">Eliminar</button> *@
                                    <a class="btn btn-sm btn-success" asp-action="Modificar" asp-route-id="@Model.Servicio.IdServicio">Modificar</a>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>


@* <div class="modal fade" id="verticalycentered" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered  modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="bi bi-exclamation-triangle"></i> Eliminar</h5>
            </div>
            <div class="modal-body">
                <div class=" d-flex w-80 justify-content-center">
                    ¿Desea eliminar el registro?
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div> *@

Sperentia - SGI/Views/Servicios/Index.cshtml
@model IEnumerable<Sperientia___SGI.Models.dbModels.Servicio>

@{
    ViewData["Title"] = "Index";
    Layout = "_LayoutAdmin";
}


<style>
    .table td, .table th {
        vertical-align: middle !important;
        text-align: center !important;
    }

    .datatable tbody td {
        cursor: pointer;
    }

</style>

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center pb-0 fs-4">Servicios</h5>

                    <div class="col-lg-12 my-5 ">
                        <button type="button" class="btn btn-success mx-2" onclick="location.href='@Url.Action("Create", "Servicios")'">
                            <i class="bi bi-folder"></i> Crear
                        </button>
                    </div>

                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Descripción</th>
                                <th>Costo</th>
                                <th>Frecuencia pago</th>
                                <th>Fecha adquisición</th>
                                <th>Cuenta</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.IdServicio</td>
                                        <td>@item.Nombre</td>
                                        <td>$@item.Costo</td>
                                        <td>@item.CostoFrecuencia</td>
                                        <td>@item.FechaAdquisicion?.ToString("dd/MM/yyyy")</td>
                                        <td>@item.CuentaRegistrada</td>
                                        <td>
                                            <a asp-action="Detalles" asp-route-id="@item.IdServicio"
                                               class="btn btn-primary rounded-pill btn-sm"><i class="bi bi-info-lg"></i></a>
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</section>

Sperentia - SGI/Views/Servicios/Modificar.cshtml
@model Sperientia___SGI.ViewModel.ServiciosViewModel

@{
    ViewData["Title"] = "Modificar Servicios";
    Layout = "_LayoutAdmin";
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card ">
                <div class="card-body ">
                    <h5 class="card-title text-center pb-0 fs-4">Modificar Servicios</h5>
                    <br />

                    <div class="m-4 d-flex  justify-content-center">
                        <form asp-action="ModificarRegistro" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="Servicio.IdServicio">


                            <div class="row mb-3">
                                <label for="nombre" class="col-md-5 col-lg-6 col-form-label">Nombre</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Nombre">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="costo" class="col-md-5 col-lg-6 col-form-label">Costo</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Costo">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="divisa" class="col-md-5 col-lg-6 col-form-label">Divisa</label>
                                <div class="col-md-7 col-lg-6">
                                    <select asp-for="Servicio.CostoDivisa" class="form-select" asp-items="Model.Divisa">
                                        <option>--Seleccione--</option>
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="frecuencia" class="col-md-5 col-lg-6 col-form-label">Frecuencia de pago</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.CostoFrecuencia">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="metodo" class="col-md-5 col-lg-6 col-form-label">Método de pago</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.MetodoPago">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="fechaA" class="col-md-5 col-lg-6 col-form-label">Fecha de adquisición</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="date" asp-for="Servicio.FechaAdquisicion">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="cuenta" class="col-md-5 col-lg-6 col-form-label">Cuenta registrada</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.CuentaRegistrada">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="contrasena" class="col-md-5 col-lg-6 col-form-label">Contraseña</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Contrasena">
                                </div>
                            </div>

                           @*  <div class="row mb-3">
                                <label for="fechaM" class="col-md-5 col-lg-6 col-form-label">Última modificación</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="date" asp-for="Servicio.UltimaModificacionContrasena">
                                </div>
                            </div> *@

                            <div class="row mb-3">
                                <label for="url" class="col-md-5 col-lg-6 col-form-label">URL</label>
                                <div class="col-md-7 col-lg-6">
                                    <input class="form-control" type="text" asp-for="Servicio.Url">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="notas" class="col-md-5 col-lg-6 col-form-label">Notas</label>
                                <div class="col-md-7 col-lg-6">
                                    <textarea class="form-control" id="floatingTextarea" style="height: 100px;" asp-for="Servicio.Notas">
                                    </textarea>
                                </div>
                            </div>

                            <br />
                            <div class="row mb-3">

                                <div class="d-inline-flex justify-content-center" role="group">
                                    <button type="button" class="btn btn-sm btn-warning me-2" onclick="location.href='@Url.Action("Index", "Servicios")'">Volver</button>
                                    <button type="submit" class="btn btn-sm btn-success">Modificar</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>